openapi: 3.0.3
info:
  title: Fruits Ecommerce Back-End API v1
  version: 1.0.11
servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: Public Endpoints
    description: All Public Endpoints


paths:
  /products:
    get:
      tags:
        - Public Endpoints
      summary: Get all products
      operationId: findAllProducts
      parameters:
        - name: page
          in: query
          description: page no.
          required: false
          schema:
            type: integer
            format: int64
            example: 1
        - name: pageSize
          in: query
          description: page size
          required: false
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductsSuccessfulResponse'

        default:
          description: Default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'

components:
  schemas:
    ProductDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          format: text
        description:
          type: string
          format: text
        unit:
          type: string
          format: text
        image_path:
          type: string
          format: text
        updatedAt:
          type: string
          format: date-time

    DefaultResponse:
      type: "object"
      required:
        - message
        - code
      properties:
        message:
          type: string
          example: "Descriptive Message Here"
        code:
          description: Status Code
          type: string
          example: "0000"



    GetProductsSuccessfulResponse:
      allOf:
        - $ref: '#/components/schemas/DefaultResponse'
        - type: "object"
          required:
            - result
          properties:
            result:
              type: array
              items:
                $ref: '#/components/schemas/ProductDto'